void main(  float4 Pos: POSITION,
			float2 tc: TEXCOORD0,
			float4 color: COLOR,
			out float4 outPos : POSITION,
			out float4 oColor : COLOR,
			out float2 outTexCoord : TEXCOORD0)
{
	//Rechteck wird so transformiert dass es das Fenster komplett ausfüllt
	Pos.xy = sign(Pos.xy);
	outPos = float4(Pos.xy, 0.0, 1.0);
	//Textur wird auf das Rechteck gemapt
	outTexCoord.x = 0.5 * (1 + Pos.x);
	outTexCoord.y = 0.5 * (1 - Pos.y);
	outTexCoord = tc;
	oColor = color;
}